### ISSUE TITLE
Adoption to faas-and-furious repo

### ISSUE THREAD

**Issue by alexellis** [kenfdev/openfaas-github-stats#1]
Hi Ken,

It'd be great to adopt this project into the faas-and-furious repo. What do you think? I've given you access, so if you'd like you can transfer it across.

Alex

**Comment by kenfdev** [comment]
sorry for the late response @alexellis !
I've transfered the repo https://github.com/faas-and-furious/faas-github-stats
and I'm going to close this one!

**Comment by alexellis** [comment]
Thanks 👍
